CREATE DATABASE shopdb;

CREATE USER 'misha'@'localhost' IDENTIFIED BY 'Qwerty1-';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON shopdb.* TO 'misha'@'localhost';